# 多链钱包生成器配置文件 - 地址匹配示例

# 生成器配置
generator:
  default_count: 1
  use_mnemonic: false
  batch_default_count: 100

# 协程池配置
worker_pool:
  auto_detect: true
  manual_count: 4
  cpu_multiplier: 2
  min_workers: 1
  max_workers: 32

# 地址匹配配置 - 启用示例
address_matching:
  # 启用地址匹配功能
  enabled: true
  # 匹配规则
  rules:
    # 寻找以"888"开头的地址
    prefixes: ["888"]
    # 寻找以"888"结尾的地址  
    suffixes: []
    # 寻找包含"love"的地址
    contains: []
    # 正则表达式：匹配连续3个或更多相同数字
    regex: ""
  # 匹配以太坊地址
  target_chains: ["eth"]
  # 最大尝试5000次
  max_attempts: 5000

# 性能测试配置
performance:
  auto_benchmark: false
  test_samples: 1000
  worker_range:
    min: 1
    max: 16
    step: 2

# 输出配置
output:
  verbose: true
  preview_count: 5
  save_to_file: false
  output_file: "wallets.json"
